-- CreateTable
CREATE TABLE "transitionMatrix" (
    "id" SERIAL NOT NULL,
    "label" TEXT NOT NULL,
    "AAA" DOUBLE PRECISION NOT NULL,
    "AA" DOUBLE PRECISION NOT NULL,
    "A" DOUBLE PRECISION NOT NULL,
    "BBB" DOUBLE PRECISION NOT NULL,
    "BB" DOUBLE PRECISION NOT NULL,
    "B" DOUBLE PRECISION NOT NULL,
    "CCC_C" DOUBLE PRECISION NOT NULL,
    "D" DOUBLE PRECISION NOT NULL,
    "NR" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "transitionMatrix_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "defaultMatrix" (
    "id" SERIAL NOT NULL,
    "label" TEXT NOT NULL,
    "y1" DOUBLE PRECISION NOT NULL,
    "y2" DOUBLE PRECISION NOT NULL,
    "y3" DOUBLE PRECISION NOT NULL,
    "y4" DOUBLE PRECISION NOT NULL,
    "y5" DOUBLE PRECISION NOT NULL,
    "y6" DOUBLE PRECISION NOT NULL,
    "y7" DOUBLE PRECISION NOT NULL,
    "y8" DOUBLE PRECISION NOT NULL,
    "y9" DOUBLE PRECISION NOT NULL,
    "y10" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "defaultMatrix_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "impliciteMatrix" (
    "id" SERIAL NOT NULL,
    "label" TEXT NOT NULL,
    "AAA" DOUBLE PRECISION NOT NULL,
    "AA" DOUBLE PRECISION NOT NULL,
    "A" DOUBLE PRECISION NOT NULL,
    "BBB" DOUBLE PRECISION NOT NULL,
    "BB" DOUBLE PRECISION NOT NULL,
    "B" DOUBLE PRECISION NOT NULL,
    "CCC_C" DOUBLE PRECISION NOT NULL,
    "D" DOUBLE PRECISION NOT NULL,
    "NR" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "impliciteMatrix_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "transitionMatrix_label_key" ON "transitionMatrix"("label");

-- CreateIndex
CREATE UNIQUE INDEX "defaultMatrix_label_key" ON "defaultMatrix"("label");

-- CreateIndex
CREATE UNIQUE INDEX "impliciteMatrix_label_key" ON "impliciteMatrix"("label");
